"""
Django settings for inventory_hub project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information:
https://docs.djangoproject.com/en/6.0/topics/settings/
"""

from pathlib import Path
import os
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# -----------------------------------
# BASE
# -----------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')

# -----------------------------------
# SECURITY
# -----------------------------------
DJANGO_ENV = os.environ.get('DJANGO_ENV', 'development').lower()
DEBUG = os.environ.get('DEBUG', 'True' if DJANGO_ENV == 'development' else 'False').lower() == 'true'

if DEBUG:
    SECRET_KEY = os.environ.get('SECRET_KEY', 'dev-only-insecure-key-change-me')
else:
    SECRET_KEY = os.environ.get('SECRET_KEY')
    if not SECRET_KEY:
        raise ImproperlyConfigured('SECRET_KEY must be set when DEBUG is False.')

raw_allowed_hosts = os.environ.get('ALLOWED_HOSTS', '')
if raw_allowed_hosts.strip():
    ALLOWED_HOSTS = [host.strip() for host in raw_allowed_hosts.split(',') if host.strip()]
else:
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost'] if DEBUG else []

# -----------------------------------
# APPLICATIONS
# -----------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'inventory',            # Core app
    'django_crontab',       # Cron jobs
    'tailwind',            # Tailwind CSS
    # 'theme',               # Tailwind app
    'django_browser_reload',  # Live reload during development
]

# -----------------------------------
# MIDDLEWARE
# -----------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'inventory_hub.urls'

# -----------------------------------
# TEMPLATES
# -----------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Global templates
        'APP_DIRS': True,                  # Look inside each app/templates/
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'inventory_hub.wsgi.application'

# -----------------------------------
# DATABASE
# -----------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'inventory_hub'),
        'USER': os.environ.get('DB_USER', 'inventory_user'),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}

# Authentication redirects
LOGIN_URL = "/"
LOGIN_REDIRECT_URL = "/dashboard/"
LOGOUT_REDIRECT_URL = "/"

# -----------------------------------
# PASSWORD VALIDATION
# -----------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# -----------------------------------
# INTERNATIONALIZATION
# -----------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# -----------------------------------
# STATIC FILES / TAILWIND
# -----------------------------------
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",  # points to inventory_hub/static/
]

# Tailwind configuration
TAILWIND_APP_NAME = 'theme'
INTERNAL_IPS = ['127.0.0.1'] 
# -----------------------------------
# EMAIL (Gmail SMTP)
# -----------------------------------
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = f'Inventory Hub <{os.environ.get("EMAIL_HOST_USER", "")}>'

# -----------------------------------
# CRON JOBS
# -----------------------------------
CRONJOBS = [
    # Run daily at 8 PM (Nepal Time 19 UTC)
    ('0 19 * * *', 'inventory.cron.check_stock_and_expiry')
]

# -----------------------------------
# DEFAULT AUTO FIELD
# -----------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'