# Generated by Django 6.0.1 on 2026-01-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_price_product_cost_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='selling_price',
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
