# Generated by Django 6.0.1 on 2026-01-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_saleitem_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minimum_stock',
            field=models.IntegerField(default=10),
        ),
    ]
