# Generated by Django 6.0.1 on 2026-01-26 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_product_minimum_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('view_profit_dashboard', 'Can view profit dashboard'), ('view_low_stock_alerts', 'Can view low stock alerts')]},
        ),
    ]
