# Generated by Django 6.0.1 on 2026-03-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_purchaseitem_quantity_alter_saleitem_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shelf_life_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='manufacture_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
