# Generated by Django 6.0.1 on 2026-03-16 02:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_product_shelf_life_days_purchaseitem_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_authorized_by',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
