# Generated by Django 6.0.1 on 2026-03-18 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_sale_discount_amount_sale_discount_authorized_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_emails', models.TextField(default='', help_text='Comma-separated email addresses.')),
                ('alert_hour', models.PositiveSmallIntegerField(default=19)),
                ('alert_minute', models.PositiveSmallIntegerField(default=0)),
                ('low_stock_enabled', models.BooleanField(default=True)),
                ('expiry_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alert Settings',
            },
        ),
    ]
