# Generated by Django 6.0.1 on 2026-03-18 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alertsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='batch_number',
            field=models.CharField(blank=True, help_text='Lot/Batch number for tracking', max_length=100),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='current_stock',
            field=models.PositiveIntegerField(default=0, help_text='Remaining stock in this specific batch'),
        ),
        migrations.CreateModel(
            name='SaleItemBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('purchase_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_sales', to='inventory.purchaseitem')),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_fulfillment', to='inventory.saleitem')),
            ],
        ),
    ]
