# Generated by Django 6.0.1 on 2026-03-19 02:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_purchaseitem_batch_number_purchaseitem_current_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='cost_at_sale',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10),
        ),
    ]
