# Generated by Django 6.0.3 on 2026-04-08 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_alter_purchaseitem_product_alter_saleitem_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('predicted_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lower_bound', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('upper_bound', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Demand Forecast',
                'verbose_name_plural': 'Demand Forecasts',
                'ordering': ['date'],
                'unique_together': {('product', 'date')},
            },
        ),
    ]
