# Generated by Django 6.0.3 on 2026-04-08 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_demandforecast'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Unique Stock Keeping Unit (e.g., from Excel)', max_length=50, null=True, unique=True),
        ),
    ]
